//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SellTables.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создай свой креатив прямо сейчас!.
        /// </summary>
        public static string AddYourCreative {
            get {
                return ResourceManager.GetString("AddYourCreative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панель администратора.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все главы.
        /// </summary>
        public static string AllChapters {
            get {
                return ResourceManager.GetString("AllChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее количество глав, которые вы создали за все время пребывания на нашем сайте. Станите ли вы обладателем самой большой коллекции глав?
        ///.
        /// </summary>
        public static string AllChaptersText {
            get {
                return ResourceManager.GetString("AllChaptersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее количество креативов.
        /// </summary>
        public static string AllCreativesCount {
            get {
                return ResourceManager.GetString("AllCreativesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее количество креативов, которые находятся в вашем портфолио. Может быть вы самый творческий человек на этом веб-сайте?.
        /// </summary>
        public static string AllCreativesText {
            get {
                return ResourceManager.GetString("AllCreativesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее количество медалей.
        /// </summary>
        public static string AllMedalsCount {
            get {
                return ResourceManager.GetString("AllMedalsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Достижения играют огромную роль  для тех, кто хочет быть первым на сайте. Может быть это вы?.
        /// </summary>
        public static string AllMedalsText {
            get {
                return ResourceManager.GetString("AllMedalsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забанить.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на от.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория:.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измените электронную почту.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить картинку.
        /// </summary>
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измените логин.
        /// </summary>
        public static string ChangeLogin {
            get {
                return ResourceManager.GetString("ChangeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измените пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Глав.
        /// </summary>
        public static string Chapters {
            get {
                return ResourceManager.GetString("Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть окно.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создайте еще одну главу.
        /// </summary>
        public static string CreateChapter {
            get {
                return ResourceManager.GetString("CreateChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создайте Ваш собственный креатив.
        /// </summary>
        public static string CreateOwnCreative {
            get {
                return ResourceManager.GetString("CreateOwnCreative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Креатива.
        /// </summary>
        public static string Creative {
            get {
                return ResourceManager.GetString("Creative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание креативы.
        /// </summary>
        public static string CreativeCreate {
            get {
                return ResourceManager.GetString("CreativeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название креативы.
        /// </summary>
        public static string CreativeName {
            get {
                return ResourceManager.GetString("CreativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Креативы.
        /// </summary>
        public static string Creatives {
            get {
                return ResourceManager.GetString("Creatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найденные по Вашему запросу креативы.
        /// </summary>
        public static string CreativesBySearch {
            get {
                return ResourceManager.GetString("CreativesBySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотри на креативы, созданные людьми.
        /// </summary>
        public static string CreativeTopInfo {
            get {
                return ResourceManager.GetString("CreativeTopInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущее количество креативов.
        /// </summary>
        public static string CurCountOfCr {
            get {
                return ResourceManager.GetString("CurCountOfCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущее количество медалей.
        /// </summary>
        public static string CurCountOfMed {
            get {
                return ResourceManager.GetString("CurCountOfMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Темный.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить пользователя.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование главы.
        /// </summary>
        public static string EditChapter {
            get {
                return ResourceManager.GetString("EditChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать профиль.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронная почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте сюда Ваши теги.
        /// </summary>
        public static string EnterYourTags {
            get {
                return ResourceManager.GetString("EnterYourTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы неудачно вошли через соц сеть.
        /// </summary>
        public static string ExternalFailute {
            get {
                return ResourceManager.GetString("ExternalFailute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название главы.
        /// </summary>
        public static string FirstChapterName {
            get {
                return ResourceManager.GetString("FirstChapterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шрифт.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы заблокированы.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш аккаунт заблокирован. Пожалуйста,попробуйте войти позже..
        /// </summary>
        public static string LockedOutText {
            get {
                return ResourceManager.GetString("LockedOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страница входа.
        /// </summary>
        public static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string LogOf {
            get {
                return ResourceManager.GetString("LogOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на в.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли должны быть одинаковы!.
        /// </summary>
        public static string PasswordEquals {
            get {
                return ResourceManager.GetString("PasswordEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создано .
        /// </summary>
        public static string PostedBy {
            get {
                return ResourceManager.GetString("PostedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Читать.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить картинку.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Масштаб.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая информация о странице пользователя.
        /// </summary>
        public static string SomeUserInfo {
            get {
                return ResourceManager.GetString("SomeUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта страница – плод моих творческих исканий. Я, так же как и вы, творческий человек, пишу креативы и увлекаюсь их созданием. И вот однажды у меня, как у нас у всех творческих личностей настал творческий ступор. Ко мне не приходили новые идеи, я совершенно обленился и думал, что больше не смогу писать. Типа поигрался и хватит, займись парень чем-нибудь серьезным. 
        ///Я не мог в это поверить и начал искать везде, где только можно, литературу о творчестве, путях выхода из творческого кризиса и просто о творческих [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string SomeUserInfoText {
            get {
                return ResourceManager.GetString("SomeUserInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка по дате создания.
        /// </summary>
        public static string SortCreateDate {
            get {
                return ResourceManager.GetString("SortCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка по дате редактирования.
        /// </summary>
        public static string SortEditDate {
            get {
                return ResourceManager.GetString("SortEditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка по имени.
        /// </summary>
        public static string SortName {
            get {
                return ResourceManager.GetString("SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на звезд.
        /// </summary>
        public static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стили.
        /// </summary>
        public static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теги.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разбанить.
        /// </summary>
        public static string Unban {
            get {
                return ResourceManager.GetString("Unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войдите через социальную сеть.
        /// </summary>
        public static string UseAnotherService {
            get {
                return ResourceManager.GetString("UseAnotherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страница пользователя.
        /// </summary>
        public static string UserPage {
            get {
                return ResourceManager.GetString("UserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страница пользователя.
        /// </summary>
        public static string UserPage1 {
            get {
                return ResourceManager.GetString("UserPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светлый.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст для главы.
        /// </summary>
        public static string YourChapterText {
            get {
                return ResourceManager.GetString("YourChapterText", resourceCulture);
            }
        }
    }
}
